In [1]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow as tf
from tensorflow.keras.layers import Normalization
from tensorflow.keras.utils import to_categorical

In [2]:
wine = pd.read_csv('../Data/Wine.csv')

In [3]:
wine.shape

(178, 14)

In [4]:
wine.head()

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   
3    14.37        1.95  2.50          16.8        113           3.85   
4    13.24        2.59  2.87          21.0        118           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1  
3   3.45     1480                 1  
4   2.93      735                 1

In [5]:
wine.describe().transpose()

count        mean         std     min       25%  \
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic_Acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Ash_Alcanity          178.0   19.494944    3.339564   10.60   17.2000   
Magnesium             178.0   99.741573   14.282484   70.00   88.0000   
Total_Phenols         178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid_Phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins       178.0    1.590899    0.572359    0.41    1.2500   
Color_Intensity       178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD280                 178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   
Customer_Segment      178.0    1.938202    0.775035    1.00    1.0000   

                          50%       75%      max  
Alcohol                13.050   13.6775    14.83  
Malic_Acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Ash_Alcanity           19.500   21.5000    30.00  
Magnesium              98.000  107.0000   162.00  
Total_Phenols           2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid_Phenols    0.340    0.4375     0.66  
Proanthocyanins         1.555    1.9500     3.58  
Color_Intensity         4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD280                   2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00  
Customer_Segment        2.000    3.0000     3.00

In [6]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64
 1   Malic_Acid            178 non-null    float64
 2   Ash                   178 non-null    float64
 3   Ash_Alcanity          178 non-null    float64
 4   Magnesium             178 non-null    int64  
 5   Total_Phenols         178 non-null    float64
 6   Flavanoids            178 non-null    float64
 7   Nonflavanoid_Phenols  178 non-null    float64
 8   Proanthocyanins       178 non-null    float64
 9   Color_Intensity       178 non-null    float64
 10  Hue                   178 non-null    float64
 11  OD280                 178 non-null    float64
 12  Proline               178 non-null    int64  
 13  Customer_Segment      178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [7]:
wine.Customer_Segment.value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [8]:
val_wine = wine.sample(frac=0.2, random_state=1000)
val_wine

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
15     13.63        1.81  2.70          17.2        112           2.85   
66     13.11        1.01  1.70          15.0         78           2.98   
165    13.73        4.36  2.26          22.5         88           1.28   
146    13.88        5.04  2.23          20.0         80           0.98   
57     13.29        1.97  2.68          16.8        102           3.00   
91     12.00        1.51  2.42          22.0         86           1.45   
130    12.86        1.35  2.32          18.0        122           1.51   
44     13.05        1.77  2.10          17.0        107           3.00   
62     13.67        1.25  1.92          18.0         94           2.10   
97     12.29        1.41  1.98          16.0         85           2.55   
139    12.84        2.96  2.61          24.0        101           2.32   
163    12.96        3.45  2.35          18.5        106           1.39   
115    11.03        1.51  2.20          21.5         85           2.46   
83     13.05        3.86  2.32          22.5         85           1.65   
68     13.34        0.94  2.36          17.0        110           2.53   
33     13.76        1.53  2.70          19.5        132           2.95   
111    12.52        2.43  2.17          21.0         88           2.55   
122    12.42        4.43  2.73          26.5        102           2.20   
70     12.29        1.61  2.21          20.4        103           1.10   
108    12.22        1.29  1.94          19.0         92           2.36   
171    12.77        2.39  2.28          19.5         86           1.39   
150    13.50        3.12  2.62          24.0        123           1.40   
28     13.87        1.90  2.80          19.4        107           2.95   
16     14.30        1.92  2.72          20.0        120           2.80   
93     12.29        2.83  2.22          18.0         88           2.45   
90     12.08        1.83  2.32          18.5         81           1.60   
112    11.76        2.68  2.92          20.0        103           1.75   
120    11.45        2.40  2.42          20.0         96           2.90   
37     13.05        1.65  2.55          18.0         98           2.45   
153    13.23        3.30  2.28          18.5         98           1.80   
52     13.82        1.75  2.42          14.0        111           3.88   
60     12.33        1.10  2.28          16.0        101           2.05   
24     13.50        1.81  2.61          20.0         96           2.53   
95     12.47        1.52  2.20          19.0        162           2.50   
102    12.34        2.45  2.46          21.0         98           2.56   
155    13.17        5.19  2.32          22.0         93           1.74   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  \
15         2.91                  0.30             1.46         7.300000   
66         3.18                  0.26             2.28         5.300000   
165        0.47                  0.52             1.15         6.620000   
146        0.34                  0.40             0.68         4.900000   
57         3.23                  0.31             1.66         6.000000   
91         1.25                  0.50             1.63         3.600000   
130        1.25                  0.21             0.94         4.100000   
44         3.00                  0.28             2.03         5.040000   
62         1.79                  0.32             0.73         3.800000   
97         2.50                  0.29             1.77         2.900000   
139        0.60                  0.53             0.81         4.920000   
163        0.70                  0.40             0.94         5.280000   
115        2.17                  0.52             2.01         1.900000   
83         1.59                  0.61             1.62         4.800000   
68         1.30                  0.55             0.42         3.170000   
33         2.74                  0.50             1.35         5.4

In [9]:
train_wine = wine.drop(val_wine.index)
train_wine

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  
177   1.60      560                 3  

[142 rows x 14 columns]

In [10]:
print(
    "Using %d samples for training and %d for validation"
    % (len(train_wine), len(val_wine))
)

Using 142 samples for training and 36 for validation


In [11]:
wine["Customer_Segment"].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [12]:
def wine_to_dataset(wine):
    wine=wine.copy()
    labels = to_categorical(wine.pop("Customer_Segment"))
    ds = tf.data.Dataset.from_tensor_slices((dict(wine),labels))
    ds = ds.shuffle(buffer_size=len(wine))
    return ds

In [13]:
train_ds = wine_to_dataset(train_wine)
val_ds = wine_to_dataset(val_wine)

In [14]:
for x, y in train_ds.take(1):
    print("Input:", x)
    print("Target:", y)

Input: {'Alcohol': <tf.Tensor: shape=(), dtype=float64, numpy=13.24>, 'Malic_Acid': <tf.Tensor: shape=(), dtype=float64, numpy=2.59>, 'Ash': <tf.Tensor: shape=(), dtype=float64, numpy=2.87>, 'Ash_Alcanity': <tf.Tensor: shape=(), dtype=float64, numpy=21.0>, 'Magnesium': <tf.Tensor: shape=(), dtype=int64, numpy=118>, 'Total_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=2.8>, 'Flavanoids': <tf.Tensor: shape=(), dtype=float64, numpy=2.69>, 'Nonflavanoid_Phenols': <tf.Tensor: shape=(), dtype=float64, numpy=0.39>, 'Proanthocyanins': <tf.Tensor: shape=(), dtype=float64, numpy=1.82>, 'Color_Intensity': <tf.Tensor: shape=(), dtype=float64, numpy=4.32>, 'Hue': <tf.Tensor: shape=(), dtype=float64, numpy=1.04>, 'OD280': <tf.Tensor: shape=(), dtype=float64, numpy=2.93>, 'Proline': <tf.Tensor: shape=(), dtype=int64, numpy=735>}
Target: tf.Tensor([0. 1. 0. 0.], shape=(4,), dtype=float32)


In [15]:
train_ds = train_ds.batch(5)
val_ds = val_ds.batch(5)

In [16]:
def encode_numerical_feature(feature, name, dataset):
    normalizer = Normalization()
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))
    normalizer.adapt(feature_ds)
    encoded_feature = normalizer(feature)
    return encoded_feature

In [17]:
alcohol= keras.Input(shape=(1,), name="Alcohol")
malic_acid= keras.Input(shape=(1,), name="Malic_Acid")
ash= keras.Input(shape=(1,), name="Ash")
ash_alcanity= keras.Input(shape=(1,), name="Ash_Alcanity")
magnesium= keras.Input(shape=(1,), name="Magnesium")
total_phenols= keras.Input(shape=(1,), name="Total_Phenols")
flavanoids= keras.Input(shape=(1,), name="Flavanoids")
nonflavanoid_phenols= keras.Input(shape=(1,), name="Nonflavanoid_Phenols")
proanthocyanins= keras.Input(shape=(1,), name="Proanthocyanins")
color_intensity= keras.Input(shape=(1,), name="Color_Intensity")
hue= keras.Input(shape=(1,), name="Hue")
od280= keras.Input(shape=(1,), name="OD280")
proline= keras.Input(shape=(1,), name="Proline")

In [18]:
all_inputs = [
    alcohol,
    malic_acid,
    ash,
    ash_alcanity,
    magnesium,
    total_phenols,
    flavanoids,
    nonflavanoid_phenols,
    proanthocyanins,
    color_intensity,
    hue,
    od280,
    proline,
]

In [19]:
# Numerical features
alcohol= encode_numerical_feature(alcohol, "Alcohol", train_ds)
malic_acid= encode_numerical_feature(malic_acid, "Malic_Acid", train_ds)
ash= encode_numerical_feature(ash, "Ash", train_ds)
ash_alcanity= encode_numerical_feature(ash_alcanity, "Ash_Alcanity", train_ds)
magnesium= encode_numerical_feature(magnesium, "Magnesium", train_ds)
total_phenols= encode_numerical_feature(total_phenols, "Total_Phenols", train_ds)
flavanoids= encode_numerical_feature(flavanoids, "Flavanoids", train_ds)
nonflavanoid_phenols= encode_numerical_feature(nonflavanoid_phenols, "Nonflavanoid_Phenols", train_ds)
proanthocyanins= encode_numerical_feature(proanthocyanins, "Proanthocyanins", train_ds)
color_intensity= encode_numerical_feature(color_intensity, "Color_Intensity", train_ds)
hue= encode_numerical_feature(hue, "Hue", train_ds)
od280= encode_numerical_feature(od280, "OD280", train_ds)
proline= encode_numerical_feature(proline, "Proline", train_ds)

In [20]:
all_features = layers.concatenate(
    [
        alcohol,
        malic_acid,
        ash,
        ash_alcanity,
        magnesium,
        total_phenols,
        flavanoids,
        nonflavanoid_phenols,
        proanthocyanins,
        color_intensity,
        hue,
        od280,
        proline,
    ]
)

In [21]:
x = layers.Dense(32, activation="relu")(all_features)
x = layers.Dropout(0.5)(x)
# PLOT TWIST #2
output = layers.Dense(4, activation="softmax")(x)
model = keras.Model(all_inputs, output)

# PLOT TWIST #3
model.compile("adam", "categorical_crossentropy", metrics=["accuracy"])

In [22]:
keras.utils.plot_model(model, show_shapes=True, rankdir="LR")

"dot" with args ['-Tps', 'C:\\Users\\WOOI_L~1\\AppData\\Local\\Temp\\tmpys1wxi3p'] returned code: 1

stdout, stderr:
 b''
b''



AssertionError: 1

In [23]:
model.fit(train_ds, epochs=100, validation_data=val_ds)

Epoch 1/100
29/29 [==============================] - 1s 8ms/step - loss: 1.2977 - accuracy: 0.4366 - val_loss: 1.0555 - val_accuracy: 0.6111
Epoch 2/100
29/29 [==============================] - 0s 2ms/step - loss: 1.0293 - accuracy: 0.5845 - val_loss: 0.8544 - val_accuracy: 0.7500
Epoch 3/100
29/29 [==============================] - 0s 3ms/step - loss: 0.8611 - accuracy: 0.6338 - val_loss: 0.7123 - val_accuracy: 0.7778
Epoch 4/100
29/29 [==============================] - 0s 2ms/step - loss: 0.6940 - accuracy: 0.7324 - val_loss: 0.6120 - val_accuracy: 0.8333
Epoch 5/100
29/29 [==============================] - 0s 2ms/step - loss: 0.5133 - accuracy: 0.8662 - val_loss: 0.5155 - val_accuracy: 0.8333
Epoch 6/100
29/29 [==============================] - 0s 2ms/step - loss: 0.4775 - accuracy: 0.8592 - val_loss: 0.4451 - val_accuracy: 0.8611
Epoch 7/100
29/29 [==============================] - 0s 3ms/step - loss: 0.4322 - accuracy: 0.8521 - val_loss: 0.3903 - val_accuracy: 0.8611
Epoch 8/100
2

Epoch 59/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0423 - accuracy: 0.9859 - val_loss: 0.1112 - val_accuracy: 0.9444
Epoch 60/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0396 - accuracy: 0.9930 - val_loss: 0.1041 - val_accuracy: 0.9444
Epoch 61/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0288 - accuracy: 1.0000 - val_loss: 0.1047 - val_accuracy: 0.9444
Epoch 62/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0366 - accuracy: 0.9930 - val_loss: 0.1010 - val_accuracy: 0.9444
Epoch 63/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0263 - accuracy: 1.0000 - val_loss: 0.1036 - val_accuracy: 0.9444
Epoch 64/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0219 - accuracy: 1.0000 - val_loss: 0.1026 - val_accuracy: 0.9444
Epoch 65/100
29/29 [==============================] - 0s 2ms/step - loss: 0.0330 - accuracy: 0.9930 - val_loss: 0.1075 - val_accuracy: 0.9444
Epoch 

In [24]:
test = wine.head(-1)
test

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
172    14.16        2.51  2.48          20.0         91           1.68   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
172        0.70                  0.44             1.24             9.70  0.62   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   

     OD280  Proline  Customer_Segment  
0     3.92     1065                 1  
1     3.40     1050                 1  
2     3.17     1185                 1  
3     3.45     1480                 1  
4     2.93      735                 1  
..     ...      ...               ...  
172   1.71      660                 3  
173   1.74      740                 3  
174   1.56      750                 3  
175   1.56      835                 3  
176   1.62      840                 3  

[177 rows x 14 columns]

In [25]:
test.drop('Customer_Segment',axis=1,inplace=True)
sample = test.to_dict('r')[0]

C:\Users\WOOI_L~1\AppData\Local\Temp/ipykernel_17176/538732817.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test.drop('Customer_Segment',axis=1,inplace=True)
C:\Users\WOOI_L~1\AppData\Local\Temp/ipykernel_17176/538732817.py:2: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  sample = test.to_dict('r')[0]


In [26]:
sample

{'Alcohol': 14.23,
 'Malic_Acid': 1.71,
 'Ash': 2.43,
 'Ash_Alcanity': 15.6,
 'Magnesium': 127,
 'Total_Phenols': 2.8,
 'Flavanoids': 3.06,
 'Nonflavanoid_Phenols': 0.28,
 'Proanthocyanins': 2.29,
 'Color_Intensity': 5.64,
 'Hue': 1.04,
 'OD280': 3.92,
 'Proline': 1065}

In [27]:
input_dict = {name: tf.convert_to_tensor([value]) for name, value in sample.items()}

In [28]:
input_dict

{'Alcohol': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([14.23], dtype=float32)>,
 'Malic_Acid': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.71], dtype=float32)>,
 'Ash': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.43], dtype=float32)>,
 'Ash_Alcanity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([15.6], dtype=float32)>,
 'Magnesium': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([127])>,
 'Total_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.8], dtype=float32)>,
 'Flavanoids': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.06], dtype=float32)>,
 'Nonflavanoid_Phenols': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.28], dtype=float32)>,
 'Proanthocyanins': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.29], dtype=float32)>,
 'Color_Intensity': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.64], dtype=float32)>,
 'Hue': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.04], dtype=float32)>,
 'OD280': 

In [29]:
predictions = model.predict(input_dict)

In [30]:
predictions

array([[1.4208085e-09, 1.0000000e+00, 1.1836978e-09, 1.6952324e-09]],
      dtype=float32)

In [31]:
 np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [32]:
for res in predictions:
    print(res)

[0.000 1.000 0.000 0.000]
